name = "GetDef"
uuid = "a709d4c7-4bd9-42a4-ae19-232071b93a9a"
authors = ["Peter Deffebach <p.deffebach@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
